log_dir = "/mnt/data/st0x-rest-api/logs"
database_url = "sqlite:///mnt/data/st0x-rest-api/st0x.db"
registry_url = "https://raw.githubusercontent.com/rainlanguage/rain.strategies/5d0a11ad4a3e89531c922317b09216200ea7bdc0/registry"
rate_limit_global_rpm = 600
rate_limit_per_key_rpm = 60
docs_dir = "/var/lib/st0x-docs"
local_db_path = "/mnt/data/st0x-rest-api/raindex.db"
