name: CI
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.ref }}-ci
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  rust-checks:
    strategy:
      matrix:
        os: [ubuntu-latest]
        task: [rs-test, rainix-rs-static]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      COMMIT_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true
            fallback = true
            sandbox = false

      - uses: cachix/cachix-action@v15
        with:
          name: albion
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - run: ./prep.sh

      - name: Run ${{ matrix.task }}
        run: nix develop -c ${{ matrix.task }}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            accept-flake-config = true

      - uses: cachix/cachix-action@v15
        with:
          name: albion
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build docs
        run: nix build .#albion-docs
